# Generated by Django 4.2 on 2024-10-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conferences_category'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='reservations',
            field=models.ManyToManyField(through='users.reservation', to='conferences.conferences'),
        ),
    ]
