# Generated by Django 4.2 on 2024-10-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conferences_category'),
        ('users', '0002_participant_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='reservations',
            field=models.ManyToManyField(related_name='reservations', through='users.reservation', to='conferences.conferences'),
        ),
    ]
